'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblStudent
    Public Property ID As Integer
    Public Property Name As String
    Public Property Gender As String
    Public Property Age As Nullable(Of Integer)
    Public Property Department_Name As Nullable(Of Integer)

    Public Overridable Property tblDepartment As tblDepartment

End Class
